### ISSUE TITLE
Extension not working

### ISSUE THREAD

**Issue by tbu-inway** [BCILITY/MandatoryFields#1]
Hello, I've problems with your extesion. I've made the setup, but nothing is shown up on Customer Card.

And on Setup Page 21 Customer Card is selected, but it's giving Vendor Card as Name.

<img width="1806" alt="image" src="https://github.com/user-attachments/assets/42baf91c-8253-46f9-b31a-31591478c093">

<img width="1806" alt="image" src="https://github.com/user-attachments/assets/f483c4a2-f49f-4e08-8e2f-7cc8fa8e278e">

<img width="1874" alt="image" src="https://github.com/user-attachments/assets/d66a5a55-23d4-4efa-a2bf-3add72e61928">

**Comment by BCILITY** [comment]
Hi @tbu-inway 
Thanks for reaching out.
Can you make sure that setup on Customer Card is enabled?
![image](https://github.com/user-attachments/assets/f363c905-72ef-4896-afba-552812d4dafa)

Also for the first picture, i think you made a mistake since first and second pictures are the same?

**Comment by tbu-inway** [comment]
Hi @BCILITY 
yes the setup is already enabled and you were right the first Screenshot should be the Setup.

<img width="719" alt="image" src="https://github.com/user-attachments/assets/0cb0c447-9ff4-41df-aebc-762c91702eff">

And as I mentioned, page 21 is selected, but it's giving the page name vendor card.

**Comment by tbu-inway** [comment]
I've unistalled and reinstall your extension and now it's working fine.
